### ISSUE TITLE
[Suggestion] Added the ability to remove options from a menu.

### ISSUE THREAD

**Issue by Slayzehh** [overextended/ox_lib#378] opened 2023-07-25 17:20 UTC
**Is your feature request related to a problem? Please describe.**

It would be great to be able to remove options from a menu.

Let's imagine that we display a list of properties, for example, and that when it's clicked, it's deleted. The problem is that we have to reopen the menu to refresh the list, which isn't practical when the menu isn't open in a function that can be called up again.

**Describe the solution you'd like**

You'd need to add a function that would allow you to remove one or more options, such as

"lib.RemoveMenuOptions('some_menu_id', 3 or {2,3})"

I think this would come in handy for a lot of people who are in the same bind as me at the moment.

Thank you in advance if this is taken into account.

**Comment by LukeWasTakenn** [comment] 2023-07-30 19:48
Duplicate of #279

**Closed by LukeWasTakenn** 2023-07-30 19:48 UTC
Labels: enhancement
