### ISSUE TITLE
[Suggestion] - Suggestion for Real-Time Menu Updates in Ox_Lib

### ISSUE THREAD

**Issue by Mesrine67** [overextended/ox_lib#600] opened 2024-06-19 11:15 UTC
### Suggestion for Real-Time Menu Updates in Ox_Lib

**Problem:**
When using the menu system provided by Ox_Lib, I cannot update the information of a menu while it is open. This limitation affects the dynamic interaction I want to create in my server. I need the ability to refresh or update the menu contents in real-time based on in-game events or data changes.

**Details:**

- **Menu Registration:** I register the menu with `lib.registerMenu`.
- **Menu Display:** The menu is displayed using `lib.showMenu`.
- **Problem:** Once the menu is open, any changes to the data (such as updating vehicle lists, player stats, etc.) are not reflected in the menu until it is closed and reopened.

**Example Use Case:**
I have a menu that lists nearby vehicles. As vehicles move in and out of the area, I need the menu to update in real-time to reflect the current state without the player having to close and reopen the menu.

**Request:**
Could you provide guidance on how to implement real-time updates to the menu contents while it is open? If this feature is not currently supported, I would like to suggest considering it for a future update. This functionality would greatly enhance the dynamic capabilities of Ox_Lib menus, providing a more seamless and interactive experience for users.

Thank you for your support and for developing such a robust library for the FiveM community.

![FiveM_b3095_GTAProcess_2024 06 19-13 09-ezgif com-video-to-gif-converter](https://github.com/overextended/ox_lib/assets/89279156/646173c7-2660-4cb3-8e16-29cf264cc7c4)

**Comment by LukeWasTakenn** [comment] 2024-07-06 19:42
duplicate of #279

**Closed by LukeWasTakenn** 2024-07-06 19:42 UTC
Labels: enhancement
