### ISSUE TITLE
[Bug] require bug when ox_lib is loaded more than once

### ISSUE THREAD

**Issue by whyauthentic** [overextended/ox_lib#545] opened 2024-04-09 16:29 UTC
**Describe the bug**
ox_inventory isn't working with the newest ox_lib Version

**To Reproduce**
1. Update ox_lib to the newest Version
2. Restart your Server
3. Join your Server
4. See error on Client Side

**Expected behavior**
Normal Loading and Function from ox_inventory

**Screenshots**
![image](https://github.com/overextended/ox_lib/assets/109388773/d14a9b3b-2805-4592-b332-16d9fafb014b)

**Comment by Manason** [comment] 2024-04-10 00:04
I am also seeing errors, affecting other resources as well.

**Comment by thelindat** [comment] 2024-04-10 04:19
![image](https://github.com/overextended/ox_lib/assets/65407488/8349620a-ec28-434a-aaa6-23715c857393)

**Comment by Manason** [comment] 2024-04-10 06:29
Here are some of the errors I'm newly seeing after updating ox_lib

https://cdn.discordapp.com/attachments/1227387291266453615/1227387291551531058/image.png?ex=6628387e&is=6615c37e&hm=d3ea32e48015a3f86dba6a258b18c3b394748d75f1f208b9ebb203e0ab9eff0f&

https://cdn.discordapp.com/attachments/1211208527822192670/1226369658182045816/image.png?ex=662484bf&is=66120fbf&hm=e662e866c33905bba761bc8b2e928519bcaf0a9e1f8401f247b9e6c03fb5d7c6&

https://cdn.discordapp.com/attachments/1118364689588572170/1227385556564967494/image.png?ex=662836e0&is=6615c1e0&hm=de93534cab82106fd9e3045daf44dcb36bb0deb795e439878f74168234aacd86&

**Comment by xPiwel** [comment] 2024-04-10 09:48
Same issue here since 3.19.0 (not fixed with 3.19.1). Works fine with 3.18.0 

![image](https://github.com/overextended/ox_lib/assets/1357325/e80648ab-fee9-48e4-8ac7-b47a8be11622)

**Comment by Envi-Scripts** [comment] 2024-04-10 14:12
Can also confirm the same issue. One thing I notice is that I cannot find the ox_lib/imports/require/client.lua in the resource anywhere and there is only a shared.lua inside that folder 


![image](https://github.com/overextended/ox_lib/assets/126303539/b642787b-6b3c-4e9b-b7e7-8fccc795dcc6)

**Comment by Manason** [comment] 2024-04-10 15:39
> Can also confirm the same issue. One thing I notice is that I cannot find the ox_lib/imports/require/client.lua in the resource anywhere and there is only a shared.lua inside that folder
> 
> ![image](https://private-user-images.githubusercontent.com/126303539/321270541-b642787b-6b3c-4e9b-b7e7-8fccc795dcc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NjM3ODUsIm5iZiI6MTcxMjc2MzQ4NSwicGF0aCI6Ii8xMjYzMDM1MzkvMzIxMjcwNTQxLWI2NDI3ODdiLTZiM2MtNGU5Yi1iN2U3LThmY2NjNzk1ZGNjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQxNTM4MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzg2YjczYmMzN2E5Y2IwZmJmYjRkZmIxOTQ0MzMxMGQyYzZmNWIyYzhjZWEyNzU5MDM4NjM3NDFlM2EyMDNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lC47LxsT58huIE7CnWQeuy1aR9ItZa99J2GDKGfLWAs)

The client.lua is not there in v3.18.0 https://github.com/overextended/ox_lib/tree/e3ece4f337bef61a19dca7bca5a6f61b73a3d72d/imports/require so it would not be related to this bug as the issues here are reproducible in v3.19 only

**Comment by thelindat** [comment] 2024-04-11 01:24
> the issues here are reproducible

Our definitions of "reproducible" are clearly very different.

The images you posted aren't even related to the issue being reported; one of them doesn't even reference ox_lib, and two of them are waitFor timeout errors due to you having too many assets loaded and failing to load more.

**Comment by thelindat** [comment] 2024-04-11 01:34
Freshly installed ESX-Ox recipe does not have the reported issue either.

![image](https://github.com/overextended/ox_lib/assets/65407488/aab7cb25-fdc7-4ff2-8a25-90d9c271a330)

**Closed** 2024-04-11 05:03 UTC
Labels: bug

**Comment by thelindat** [comment] 2024-04-11 05:06
> Normal Loading and Function from ox_inventory

As shown in your stack trace the error is in ox_target and not ox_inventory; it's also only an issue in older versions of ox_target and was fixed with [v1.14.0](https://github.com/overextended/ox_target/releases/tag/v1.14.0).
