### ISSUE TITLE
[Suggestion] Remember previous radial menu page when going back

### ISSUE THREAD

**Issue by Moozdzn** [overextended/ox_lib#242] opened 2023-02-23 17:04 UTC
**Is your feature request related to a problem? Please describe.**
Currently when going back to the previous menu it opens of the first page, even if the option was in one of the 'more' menu

**Describe the solution you'd like**
[What happens now](https://streamable.com/vz402n)
I think it would make sense when leaving the menu with the 'Frisk' options, the prev menu should be the one with 'Police 8' instead of having to click the more button again

**Comment by LukeWasTakenn** [comment] 2023-02-25 13:16
Should be resolved in 709d512...?

Could you double check it works as intended?

**Comment by Moozdzn** [comment] 2023-02-25 13:30
Don't think so, give me a minute to give you some steps so you can test it yourself

**Comment by Moozdzn** [comment] 2023-02-25 13:35
```lua
lib.registerRadial({
    id = "pet_interactions",
    items = {
        {
            icon = "dog",
            label = "call_pet",
            onSelect = function()
                TriggerEvent("pets:client:callPet")
            end
        },
        {
            icon = "hand",
            label = "dismiss_pet",
            onSelect = function()
                TriggerEvent("pets:client:dismissPet")
            end
        },
        {
            icon = "bone",
            label = "feed_pet",
            onSelect = function()
                TriggerEvent("pets:client:feedPet")
            end
        },
        {
            icon = "thumbs-up",
            label = "come",
            onSelect = function()
                TriggerEvent("pets:client:petFollow")
            end
        },
        {
            icon = "thumbs-down",
            label = "stay",
            onSelect = function()
                TriggerEvent("pets:client:petUnfollow")
            end
        },
        {
            icon = "car",
            label = "command_enter_car",
            onSelect = function()
                TriggerEvent("pets:client:enterCarPet")
            end
        },
        {
            icon = "user-shield",
            label = "toggle_defense_mode",
            onSelect = function()
                TriggerEvent("pets:client:toggleDefendMode")
            end
        },
        {
            icon = "ban",
            label = "cancel_command",
            onSelect = function()
                TriggerEvent("pets:client:resetPet")
            end
        },
        {
            icon = "hand-point-down",
            label = "order_sit",
            onSelect = function()
                TriggerEvent("pets:client:sitPet")
            end
        },
        {
            icon = "hand-holding",
            label = "order_lay_down",
            onSelect = function()
                TriggerEvent("pets:client:layPet")
            end
        },
        {
            icon = "exclamation",
            label = "order_bark",
            onSelect = function()
                TriggerEvent("pets:client:barkPet")
            end
        },
        {
            icon = "paw",
            label = "order_paw",
            onSelect = function()
                TriggerEvent("pets:client:pawPet")
            end
        },
        {
            icon = "user-ninja",
            label = "order_taunt",
            onSelect = function()
                TriggerEvent("pets:client:tauntPet")
            end
        }
    }
})


lib.addRadialItem({
	id = "pet",
	icon = "paw",
	label = _U("pet_interaction"),
	menu = "pet_interactions"
})
```

1. Register menu/items above
2. Open Pet menu
3. Click more
4. Go back

Its going back to the global radial menu and the center icon is a go back button that doesn't do anything

**Comment by LukeWasTakenn** [comment] 2023-02-25 14:38
Reverted the commit for now, seems the issue is a lot more complex than I originally thought so will probably have to be looked into in the future.

**Comment by Moozdzn** [comment] 2023-02-25 14:59
I’ll also give it a go when I can.

**Closed** 2023-02-28 19:47 UTC
Labels: enhancement
