### ISSUE TITLE
[Suggestion] Set client locale by script

### ISSUE THREAD

**Issue by Skryptific** [overextended/ox_lib#472] opened 2023-12-21 19:43 UTC
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to set a locale using a script, it is preset using a convar. It would be cool to be able to set the locale on the client side so developers can create a "language selector" script so players can set their own language.

**Describe the solution you'd like**
setLocale/setLanguage (or whatever) function that updates the language without having to re-log or anything.

**Additional context**
This would be useful for servers who have multi-language players so their players can set their own preferred language when implemented by a developer.

**Comment by thelindat** [comment] 2024-01-15 23:00
Duplicate of #435.

**Closed by thelindat** 2024-01-15 23:00 UTC
Labels: enhancement
